# Generated by Django 3.2.6 on 2021-11-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartsAuthority',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('line', models.CharField(blank=True, max_length=100, null=True, verbose_name='Line')),
                ('part', models.CharField(blank=True, max_length=100, null=True, verbose_name='Part')),
                ('cost', models.FloatField(blank=True, verbose_name='Cost')),
                ('coreprice', models.FloatField(verbose_name='Coreprice')),
                ('qtyonhand', models.IntegerField(blank=True, null=True, verbose_name='Qtyonhand')),
                ('packs', models.IntegerField(blank=True, null=True, verbose_name='Packs')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shopify',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('handle', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('bodyHTML', models.TextField(blank=True, null=True, verbose_name='Body (HTML)')),
                ('vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('standard_product_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Standard Product Type')),
                ('custom_product_type', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('published', models.CharField(blank=True, max_length=200, null=True)),
                ('option1_name', models.CharField(blank=True, max_length=200, null=True)),
                ('option1_value', models.CharField(blank=True, max_length=200, null=True)),
                ('option2_name', models.CharField(blank=True, max_length=200, null=True)),
                ('option2_value', models.CharField(blank=True, max_length=200, null=True)),
                ('option3_name', models.CharField(blank=True, max_length=200, null=True)),
                ('option3_value', models.CharField(blank=True, max_length=200, null=True)),
                ('variant_sku', models.CharField(blank=True, max_length=200, null=True)),
                ('variant_grams', models.CharField(blank=True, max_length=200, null=True)),
                ('variant_inventory_tracker', models.CharField(blank=True, max_length=200, null=True)),
                ('variant_inventory_qty', models.CharField(blank=True, max_length=200, null=True)),
                ('variant_inventory_policy', models.CharField(blank=True, max_length=200, null=True)),
                ('variant_fulfillment_service', models.CharField(blank=True, max_length=200, null=True)),
                ('variant_price', models.CharField(blank=True, max_length=200, null=True)),
                ('variant_compare_at_price', models.CharField(blank=True, max_length=200, null=True)),
                ('variant_requires_shipping', models.CharField(blank=True, max_length=200, null=True)),
                ('variant_taxable', models.CharField(blank=True, max_length=200, null=True)),
                ('variant_barcode', models.CharField(blank=True, max_length=200, null=True)),
                ('image_src', models.CharField(blank=True, max_length=500, null=True)),
                ('image_position', models.CharField(blank=True, max_length=200, null=True)),
                ('image_alt_text', models.CharField(blank=True, max_length=200, null=True)),
                ('gift_card', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=200, null=True)),
                ('google_shopping_google_product_category', models.CharField(blank=True, max_length=200, null=True)),
                ('google_shopping_gender', models.CharField(blank=True, max_length=200, null=True)),
                ('google_shopping_age_group', models.CharField(blank=True, max_length=200, null=True)),
                ('google_shopping_MPN', models.CharField(blank=True, max_length=200, null=True)),
                ('google_shopping_adWords_grouping', models.CharField(blank=True, max_length=200, null=True)),
                ('google_shopping_adWords_labels', models.CharField(blank=True, max_length=200, null=True)),
                ('google_shopping_condition', models.CharField(blank=True, max_length=200, null=True)),
                ('google_shopping_custom_product', models.CharField(blank=True, max_length=200, null=True)),
                ('google_shopping_custom_label_0', models.CharField(blank=True, max_length=200, null=True)),
                ('google_shopping_custom_label_1', models.CharField(blank=True, max_length=200, null=True)),
                ('google_shopping_custom_label_2', models.CharField(blank=True, max_length=200, null=True)),
                ('google_shopping_custom_label_3', models.CharField(blank=True, max_length=200, null=True)),
                ('google_shopping_custom_label_4', models.CharField(blank=True, max_length=200, null=True)),
                ('variant_image', models.CharField(blank=True, max_length=200, null=True)),
                ('variant_weight_unit', models.CharField(blank=True, max_length=200, null=True)),
                ('variant_tax_code', models.CharField(blank=True, max_length=200, null=True)),
                ('cost_per_item', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
