# Generated by Django 3.2.6 on 2021-11-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_excel', '0004_alter_partsauthority_coreprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsauthority',
            name='coreprice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Coreprice'),
        ),
        migrations.AlterField(
            model_name='partsauthority',
            name='cost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='partsauthority',
            name='packs',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Packs'),
        ),
        migrations.AlterField(
            model_name='partsauthority',
            name='qtyonhand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qtyonhand'),
        ),
    ]
